version: "3.8"

x-postgres-variables: &postgres-variables
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

services:
  web:
    build:
      context: ./web
      target: dev
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "1300:80"
  app:
    build:
      context: .
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      <<: *postgres-variables
      DJ_ALLOWED_HOSTS: ${DJ_ALLOWED_HOSTS}
      DJ_CORS_ORIGIN_WHITELIST: ${DJ_CORS_ORIGIN_WHITELIST}
      DJ_DATABASE_HOST: db
      DJ_DATABASE_PORT: 5432
      DJ_DEBUG: "True"
      DJ_SECRET_KEY: ${DJ_SECRET_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - web
    volumes:
      - ./:/code
      - static_volume:/code/static
      - media_volume:/code/media
  db:
    image: postgres
    restart: always
    environment: *postgres-variables
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  db_volume:
