version: "3.8"

x-postgres-variables: &postgres-variables
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

services:
  web:
    build:
      context: ./web
      target: prod
    environment:
      WEB_API_HOST: ${COMPOSE_WEB_API_HOST}
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "${COMPOSE_WEB_PORT}:80"
  app:
    build:
      context: .
      target: prod
    command: gunicorn izba_docs.wsgi:application --bind 0.0.0.0:8000
    environment:
      <<: *postgres-variables
      DJ_ALLOWED_HOSTS: ${DJ_ALLOWED_HOSTS}
      DJ_DATABASE_HOST: db
      DJ_DATABASE_PORT: 5432
      DJ_DEBUG: "False"
      DJ_SECRET_KEY: ${DJ_SECRET_KEY}
    ports:
      - "${COMPOSE_APP_PORT}:8000"
    depends_on:
      - db
      - web
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
  db:
    image: postgres
    restart: always
    environment: *postgres-variables
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  db_volume:
