version: "3.8"
services:
  web:
    build:
      context: ./web
      target: dev
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "1300:80"
  app:
    build:
      context: .
      target: dev
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: 1
    ports:
      - "8000:8000"
    depends_on:
      - db
      - web
    volumes:
      - ./:/code
      - static_volume:/code/static
      - media_volume:/code/media
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  db_volume:
