version: "3.8"
services:
  web:
    build:
      context: ./web
      target: prod
    restart: always
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - "${WEB_PORT}:80"
  app:
    build:
      context: .
      target: prod
    command: gunicorn izba_docs.wsgi:application --bind 0.0.0.0:8000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: 0
    ports:
      - "${APP_PORT}:8000"
    depends_on:
      - db
      - web
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  db_volume:
