version: "3"
services:
  proxy:
    build:
      context: ./proxy
    restart: always
    volumes:
      - static_volume:/usr/local/src/app/static
      - media_volume:/usr/local/src/app/media
    ports:
      - ${PROXY_PORT}:80
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        GIT_USER_NAME: ${GIT_USER_NAME}
        GIT_USER_EMAIL: ${GIT_USER_EMAIL}
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: 1
    ports:
      - 8000:8000
    depends_on:
      # - db
      - proxy
    volumes:
      - static_volume:/usr/local/src/app/static
      - media_volume:/usr/local/src/app/media
    volumes:
      - $PWD:/code
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - db_volume:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  # db_volume:
